project:
  type: website
  output-dir: docs

# Meta
description-meta: "Prof. Dr. Christian Rauh"
author-meta: "Christian Rauh"

website:
  title: "Christian Rauh"
  image: files/images/CR_card.png
  description: "Personal website of Prof. Dr. Christian Rauh"
  favicon: files/favicon_CR.png
 
  navbar:
    background: "#003399"  # You can change the background color here
    foreground: white

    left:   # You can comment out all navigation items here if you just like to keep the index page only
#      - text: Home
#        href: index.qmd
      - text: Experience
        href: experience.qmd             
      - text: Publications
        href: publications.qmd
      - text: Data & Resources
        href: data-and-resources.qmd
      - text: Teaching
        href: teaching.qmd
      - text: Blog et al.
        href: blog.qmd                   


    right: 
      - text: <strong>CV</strong>
        href: files/CV_Rauh_EN.pdf 
      - icon: envelope
        href: mailto:christian.rauh@wzb.eu 
      - icon: linkedin
        href: https://www.linkedin.com/in/chrauh/
        target: _blank
      - icon: github
        href: http://www.github.com/ChRauh
        target: _blank
  
  page-navigation: true
  
  page-footer: 
    left: "![](/files/favicon_CR.png){width=30px height=30px}  [Christian Rauh](http://www.github.com/ChRauh) &copy; <script>document.write(new Date().getFullYear())</script>" 
    center: ""
    right:  
      - icon: envelope
        href: mailto:christian.rauh@wzb.eu 
      - icon: linkedin
        href: https://www.linkedin.com/in/chrauh/
        target: _blank
      - icon: github
        href: http://www.github.com/ChRauh
        target: _blank

  
  search:
    location: navbar
    type: textbox
  
  reader-mode: false

  draft-mode: visible
  
  repo-url: https://github.com/ChRauh/ChRauh.github.io
#  repo-actions: [edit, issue, source]
  
  open-graph: true
  
  twitter-card: true 
#  card-style: summary      
  
  site-url: "https://chrauh.github.io/"
  
  google-analytics:
    tracking-id: ""  # Please delete or replace with your own tracking ID
    anonymize-ip: true 

bibliography: references.bib  # Add references.bib to the root folder to enable the bibliography function

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript
    link-external-filter: '^(?:http:|https:)\/\/chrauh\.github\.io\/custom'
    include-in-header: "files/includes/_academic.qmd"

