project:
  type: website
  output-dir: docs

# Meta
description-meta: "Prof. Dr. Christian Rauh"
author-meta: "Christian Rauh"

execute:
  freeze: false
  cache: false

# SEO niceties
sitemap: true
lang: en

website:
  title: "Christian Rauh"
  description: "Personal website of Prof. Dr. Christian Rauh"
  image: /files/images/CR_card.png         
  favicon: /files/favicon_CR.png           
  site-url: "https://christian-rauh.eu"    
  
  # Robots.txt - allowing bots to crawl - manually created
  # robots: |
  #   User-agent: *
  #   Allow: /
  #   Sitemap: https://chrauh.github.io/sitemap.xml

  navbar:
    background: "#003399"
    foreground: white
    left:
      - text: Experience
        href: experience.qmd
      - text: Publications
        href: publications.qmd
      - text: Data & Resources
        href: data-and-resources.qmd
      - text: Teaching
        href: teaching.qmd
      - text: Blog et al.
        href: blog.qmd
    right:
      - text: <strong>CV</strong>
        href: https://christian-rauh.eu/experience.html#full-cv
      - icon: envelope
        href: mailto:christian.rauh@wzb.eu
      - icon: linkedin
        href: https://www.linkedin.com/in/chrauh/
        target: _blank
      - icon: github
        href: https://github.com/ChRauh         # use https
        target: _blank

  page-navigation: true

  page-footer:
    left: "![](/files/favicon_CR.png){width=30px height=30px}  [Christian Rauh](https://github.com/ChRauh) &copy; <script>document.write(new Date().getFullYear())</script>"
    center: ""
    right:
      - icon: envelope
        href: mailto:christian.rauh@wzb.eu
      - icon: linkedin
        href: https://www.linkedin.com/in/chrauh/
        target: _blank
      - icon: github
        href: https://github.com/ChRauh
        target: _blank

  search:
    location: navbar
    type: textbox

  reader-mode: false
  draft-mode: visible                         # consider removing for prod

  repo-url: https://github.com/ChRauh/ChRauh.github.io
  # repo-actions: [source, issue]             # optional, handy on pages

  # Social cards — explicit and absolute (key to fixing previews)
  open-graph:
    image: /files/images/CR_card.png
  twitter-card:
    image: /files/images/CR_card.png
    card-style: summary_large_image

  # google-analytics:                           # remove if unused, GA analytics under GDPR only with explicit consent!
    # tracking-id: "G-XXXXXXX"
    # anonymize-ip: true

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript
    link-external-filter: '^(?:http:|https:)\/\/chrauh\.github\.io\/custom'
    include-in-header: "files/includes/_academic.qmd"
    anchor-sections: true                     # nice for deep-linking


